# add your settings here (overriding the defaults)

biocypher:
  offline: false            
  debug: false
  schema_config_path: config/schema_config.yaml
  output_directory: ./output_human  

neo4j:
  uri: bolt://neo4j:7687
  user: neo4j
  password: myNewPass456
  database_name: neo4j
  wipe: true                
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true